name: Deploy to Kubero

on:
  workflow_run:
    workflows: ["GHCR Images"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-kubero:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy Client en Kubero
        run: |
          curl -s -o /dev/null -w "Client: %{http_code}\n" -X GET \
            "https://kubero.inf.uct.cl/api/apps/ramtun/production/client/restart" \
            -H "Authorization: Bearer ${{ secrets.KUBERO_TOKEN }}"

      - name: Redeploy Server en Kubero
        run: |
          curl -s -o /dev/null -w "Server: %{http_code}\n" -X GET \
            "https://kubero.inf.uct.cl/api/apps/ramtun/production/server/restart" \
            -H "Authorization: Bearer ${{ secrets.KUBERO_TOKEN }}"
